language: go

os:
  - linux

dist: xenial
addons:
  apt:
    packages:
    - libsystemd-dev

go:
  - 1.11.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  global:
    GO111MODULE=on

notifications:
  email:
    on_success: change
    on_failure: always

script: go build
